# Generated by Django 5.1.1 on 2024-10-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0004_alter_framer_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framer_profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='farmer_profilepic'),
        ),
    ]
