# Generated by Django 5.1.1 on 2024-10-01 12:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0005_alter_framer_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Framer_profile',
            new_name='Farmer_profile',
        ),
    ]
