# Generated by Django 5.1.1 on 2024-10-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0008_products_quantity_alter_products_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_id',
            field=models.CharField(default=0, editable=False, max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
