# Generated by Django 5.1.1 on 2024-09-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_user', '0002_rename_city_public_user_address_public_user_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='public_user',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='public_user',
            name='pincode',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
