# Generated by Django 5.1.1 on 2024-09-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_user', '0003_public_user_city_public_user_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public_user',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='public_user',
            name='pincode',
            field=models.CharField(max_length=30),
        ),
    ]
