# Generated by Django 5.1.1 on 2024-10-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_user', '0005_public_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public_profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='publicuser_profilepic/'),
        ),
    ]
