# Generated by Django 5.1.1 on 2024-10-19 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmer', '0011_alter_products_product_id'),
        ('orders', '0002_remove_products_farmer_delete_orders_delete_products'),
        ('public_user', '0007_alter_public_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], max_length=50)),
                ('shipping_address', models.TextField(null=True)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Sucessful', 'Sucessful'), ('Failed', 'Failed')], max_length=50)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Netbanking', 'Netbanking'), ('UPI', 'UPI')], max_length=50)),
                ('farmer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer.farmer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer.products')),
                ('public_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='public_user.public_user')),
            ],
        ),
    ]
