# Generated by Django 5.1.1 on 2024-10-19 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0011_alter_products_product_id'),
        ('orders', '0003_initial'),
        ('public_user', '0007_alter_public_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.farmer'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.products'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='public_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_user.public_user'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shipping_address',
            field=models.TextField(),
        ),
    ]
