# Generated by Django 5.1.1 on 2024-10-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orders_farmer_alter_orders_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='estimated_delivery_date',
            field=models.DateTimeField(null=True),
        ),
    ]
