# Generated by Django 5.1.1 on 2024-10-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orders_estimated_delivery_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='shipping_address',
            new_name='delivery_address',
        ),
        migrations.AddField(
            model_name='orders',
            name='current_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='current_phonenumber',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='delivered_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='username',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
