# Generated by Django 5.1.1 on 2024-10-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_shipping_address_orders_delivery_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
    ]
