# Generated by Django 5.1.1 on 2024-10-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orders_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='current_phonenumber',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='orders',
            name='pincode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='username',
            field=models.CharField(max_length=250),
        ),
    ]
