# Generated by Django 5.1.1 on 2024-10-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_orders_delivery_charge_orders_tax_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('confirmed', 'confirmed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], max_length=50),
        ),
    ]
