# Generated by Django 5.1.1 on 2024-10-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
            preserve_default=False,
        ),
    ]
